name: Anovos Demo

on:
  release:
  push:
    paths:
      - 'demo/**'
#    branches:
#      - main


jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB_CREDENTIALS

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: demo/
          push: ${{ startsWith(github.ref, 'refs/tags') }}
          tags: anovos-spark-demo:${{ github.ref_name }}
