name: Unit Test

on:
  push:
    paths:
      - 'requirements.txt'
      - 'src/**'
      - '!**.md'
      - '!.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - python: '3.7'
            spark: '2.4.8'
            hadoop: '2.7'
            java: '8'
            experimental: false
          - python: '3.9'
            spark: '3.1.3'
            hadoop: '3.2'
            java: '11'
            experimental: false
          - python: '3.9'
            spark: '3.2.1'
            hadoop: '3.2'
            java: '11'
            experimental: false
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - uses: vemonet/setup-spark@v1
        with:
          spark-version: ${{ matrix.spark }}
          hadoop-version: ${{ matrix.hadoop }}

      - name: Checkout code
        uses: actions/checkout@master

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov wheel
          pip install -r requirements.txt

      - name: Check SPARK_HOME
        run: |
          echo $SPARK_HOME
          ls $SPARK_HOME

      - name: Run the unit tests for data_ingest module
        run: |
          pytest -v --cov=src/main/anovos src/test/anovos/data_ingest

      - name: Run the unit tests for data_analyzer module 
        run: |
          pytest -v --cov=src/main/anovos src/test/anovos/data_analyzer

      - name: Run the unit tests for drift module
        run: |
          pytest -v --cov=src/main/anovos src/test/anovos/drift

      - name: Run the unit tests for transformers module
        run: |
          pytest -v --cov=src/main/anovos src/test/anovos/data_transformer